server:
  port: 8080

#指定mybatis映射文件（mapper.xml）的路径
mybatis:
  mapper-location: classpath*:com/feng/edu/mapper/*Mapper.xml
#  type-aliases-package: com.feng.edu.entity
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456